[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    crankyoldgit/IRremoteESP8266@^2.8.6
    tzapu/WiFiManager@^2.0.17
